Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,10 +26,16 @@ jobs:
 
     - name: Search and Audit Cargo Projects
       run: |
+        audit_failures=0
         for cargo_toml in $(find . -name 'Cargo.toml'); do
           dir=$(dirname $cargo_toml)
           echo "Running cargo audit in $dir"
-          (cd $dir && cargo generate-lockfile && cargo audit)
+          (cd $dir && cargo generate-lockfile && cargo audit) || audit_failures=$((audit_failures+1))
         done
+        if [ $audit_failures -ne 0 ]; then
+          echo "Cargo audit found vulnerabilities in $audit_failures projects"
+          exit 1
+        fi
+
 
 
